### PR TITLE
Add NickServ CERT IDENTIFY support

### PR DESCRIPTION
**Pull request by GLolol**
Pulled from https://bitbucket.org/chatlounge/chatservices/commits/64ccf62d43681d92675ed97c4cf30fb20216cce8, with formatting fixes.

### CODE REVIEW

**Comment by ilbelkyr** [comment]
As per the discussion on atheme/atheme#415, I'm not entirely sure about this yet. I'd prefer pushing for SASL reauth support in clients instead.

**Comment by Mikaela** [comment]
:+1: for SASL REAUTH. Does any client support it yet? I am aware of some clients having issue about it, but nothing more.

* https://github.com/ProgVal/Limnoria/issues/1095
* https://github.com/weechat/weechat/issues/413
* https://github.com/znc/znc/issues/949
* https://github.com/irssi/irssi/issues/4#issuecomment-98157005

**Comment by GLolol** [comment]
Right now, NickServ CERT is a completely different implementation from SASL, and there might still be some time before mainstream clients implement REAUTH. My reasoning for this is that 1) it makes logging in easier and 2) to bridge the gap until REAUTH or something similar is widely available for CertFP users.

**Comment by Mikaela** [comment]
I think CERT is mostly used with SASL EXTERNAL which would benefit from SASL REAUTH. I agree with 1, but in addition to 2 I think it also gives developers an excuse to not implement REAUTH

**Comment by GLolol** [comment]
If a client is only using CertFP without SASL, would REAUTH-like behavior still be available?

**Comment by Mikaela** [comment]
Probably not, but that would be a reason to start supporting SASL and REAUTH.

**Comment by GLolol** [comment]
So it still doesn't give a way for CertFP clients to identify.

> I think it also gives developers an excuse to not implement REAUTH.

What developers choose to implement is really up to them. But this enhances a feature that already exists without having to add new code.

**Comment by Mikaela** [comment]
> What developers choose to implement is really up to them. But this enhances a feature that already exists without having to add new code.

How often would this be needed? I can think of two situations:

* client is already connected with certfp and another connection adds the certificate to NickServ.
    * Why would someone do this and not `/ns cert add` without the fingerprint so current one would be added?
* the user does `/ns logout`
    * How often does anyone do this? I think average user either uses SASL or CertFP to be automatically identified and stays identified until quitting and then coming back still identifying automatically.

**Comment by GLolol** [comment]
I was thinking when services go down and don't remember identification when they restart.

**Comment by Mikaela** [comment]
> I was thinking when services go down and don't remember identification when they restart.

CertFP identifies you automatically in this case and before both client and server support SASL REAUTH this is the only way to get identified automatically.

This is also the reason why I recommend everyone who wonders which is better at \#freenode to use SASL PLAIN + CertFP.

**Comment by GLolol** [comment]
I don't recall CertFP with auto identification ever working for me.

**Comment by kaniini** [comment]
CertFP clients should declare their intent to use CertFP by using `AUTHENTICATE EXTERNAL`.  CertFP clients which do not explicitly request CertFP (and thus get it by side effect) are broken per IRCv3.2.

SASL REAUTH just means that (re-)authentication can happen after registration, there is no prerequisite requirement to have priorly authenticated, meaning that they would just do the `AUTHENTICATE EXTERNAL` exchange after registration.

**Comment by GLolol** [comment]
sweet

**Pull request closed without merging**
